# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_call

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: alpine:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.


# name: JSON test

# on:
#   - workflow_dispatch
#   - push

# env:
#   JSON: '{
#     "main":"/path/for/main/branch",
#     "dev": "/path/dev"
#   }'

# jobs:
#   json-test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: JSON
#         run: |
#           BRANCH=${GITHUB_REF##*/}
#           echo "BRANCH=$BRANCH" >> $GITHUB_ENV
#           echo ${{fromJson(env.JSON)[env.BRANCH]}}
