name: JSON test

on:
  - workflow_dispatch
  - push

env:
  JSON: '{
    "foo":"FOO",
    "bar": "BAR"
  }'
  PROP: foo

jobs:
  json-test:
    runs-on: ubuntu-latest
    steps:
      - name: JSON
        run: |
          echo ${{fromJson(env.JSON)[env.PROP]}}
