name: JSON test

on:
  - workflow_dispatch
  - push

env:
  JSON: '{
    "foo":"FOO",
    "bar": "BAR"
  }'

jobs:
  json-test:
    runs-on: ubuntu-latest
    steps:
      - name: JSON
        run: |
          PROP=bar
          echo ${{fromJson(env.JSON)[$PROP]}}
